travis:
  secure:
    BINSTAR_TOKEN: MM/n4+cc66XzY38Lqwevc5jrI7Q0xJEkyW65h8X0d2mkZZ0BGkt+lNq+BrIF/0iocgnpFFIuHfUGXJVkSlyZp0BWsRQPiR55YegthNoqhlfxgeAmeV4gUbdyI9S8DsHsG5FJe5BkjfhFOyNMjQJ8CuoS1NqleB/oAM/PfIGUYfVGglnyxadJLOP2HbZGxVPr5OrqKM0ap6XOEpdg0N43KVpEhIw9BTWJRIJkrw1LC1+vfIkIpa8hQbJaEYbxTfppB+vTFxGml6x+bwSEIck23iheNVeVgzOBiNmNeMgK/s+PrPYSlMs/b8/rcxrSBz0MNU3Y/cJbKundT0aU/Okt8D8r3bO0dkGfpIvW+vRYYDwIJa39qa7AqYdSkKQelTTBQYwXZlYfDxLYNIxXT5MMnfNAw/xIpxkWQt1FGHeq/w4YaaBOxdQww76sRH63x7EowsTSlaL6LEnztu+QX9jiJ0FW0ZRA8r691GZ0PNWNhGLgQEetOI1d88AMKfnFaed+wtfJkGRBv2RQjTnE/Sq2fqW4Fl1qV+5xvX65WQ1JBMAYkD7TTONaXC6l2w4dXZ3Oj3ryWaO+H/Dj9Y25kUAM2MUVVzbva+/0jpyk56pV6M42qHljB6WBVg69Qk2/xrOAKXW/wUFnm5ryLpPhX/C8TM1mJgnsyZaeRea8eMmDOm0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
