travis:
  secure:
    BINSTAR_TOKEN: BjTwW0yAkJoJdFrnAvjrOpnlP29knm85ujTtg9VDYiXa9Crw73Y1+xJcS7XHkDoQv5QsdHIpMREb+FugH+rvxVi8fsRP3uxC955T+0KhBNgJFbbZEhwsiuMlI+qKaQzvHEX9y2ztkuhddN96NvycqfW3lNlqtEr/UHihAV/QDp34LX4JR/KqRiFLENCePV1ZKp2ScHNoVnUmuu48UHcbwM4yMo39tv6SCLm4diZydCrPiNxfY9vZrM9qeVaXuDGUmPogx1kOdYOUhb5Hz3Trh9FJMYokN9Wi3uI75gd3ScWeEjzGXVsVCAkuxGhAdan5/BaRpP1IR0uOYEM4TIXq2Gn4RVg93SNAl+axcfTPBq8/DsgC/gEV+W40nzOAPxAmj7p/Pxg9btsEVe3DtQNxYA9iaRKXHGmMLolVgh/BUJfAdRxcYerzjpNCTv8PN28fA86BlWf/Icm/RFM/djUaBKrAzUrNtCU5B8M2sIhi/KDZDwZg5mcSQJL5+VpEty38vlk4ifFglO9h4sPkm2Msl6OUDRN+cEg7n29YRsUG3KQf+Kzj35Ol4KX8Lk0AqN8cl7VvquMrSt+zVcmoCb/Hhlqxn07ZtbB6ym9oIkMe2TClbR/En+kLn/e3yRVwKF7L1oW2qg6VgZIlxatChtvaI/rj78pVUCrG/cZN/ygqtQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
